### ISSUE TITLE
Re-add maintainers to repo

### ISSUE THREAD

**Issue by bitbacchus** [ropensci/nlrx#64]
Unfortunately (and a bit surprising) I got removed from ropensci, because I had not enabled 2FA. This happened, as far as I am aware to most (all?) co-developers and as a result, our packages `nlrx`, `NLMR`, and `landscapetools` are without maintainers that have full access to the repo, at the moment...

I now enabled 2FA, so can please s/o re-add me to ropensci? I think only @maelle can do this at the moment.

Thanks,
Sebastian

**Comment by maelle** [comment]
Done! 

I sent you an email on April 1st (to the email listed for your GitHub account). Beside I see you are not in rOpenSci slack workspace: do you need/want an invitation? 

Thanks for enabling 2FA and your understanding!

**Comment by maelle** [comment]
To other developers of these packages: please ping me here or on Slack or via `maelle@ropensci.org` once you have enabled 2FA and I'll re-instate you ASAP.

**Comment by bitbacchus** [comment]
Thanks, @maelle :-)  

I checked my emails but couldn't find any, not in my archives nor in the junk folder. You didn't get any bounces either? 
A Slack invitation would be great :+1:  

I still can't find ropensci in organizations in my profile and also can't edit code in the repo. Should this be in effect instantly or shall I wait until tomorrow or so?

**Comment by maelle** [comment]
You should have gotten an invitation from GitHub to the organization, where you usually receive emails from GitHub. :thinking: 

![image](https://user-images.githubusercontent.com/8360597/167174636-06112f43-7193-4460-a8a5-cc1719f34dd8.png)

If I send you a Slack invite, to what email address? (I'll do it first thing next week)

**Comment by maelle** [comment]
If you change your email address with GitHub, you can tell me to re-issue the organization invitation if that can help.

**Comment by mhesselbarth** [comment]
Ping for repository accesss

**Comment by maelle** [comment]
@mhesselbarth I've sent an invitation to re-instate you :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/8360597/167189148-1df7f488-0d5d-4734-ae34-6670006821f1.png)

@bitbacchus I really hope you'll get in soon!

**Comment by mhesselbarth** [comment]
Thank you!

**Comment by maelle** [comment]
@mhesselbarth I can also send an invitation to rOpenSci Slack on Monday to the email address of your choice.

**Comment by mhesselbarth** [comment]
That would be great: mhk.hesselbarth@gmail.com

**Comment by bitbacchus** [comment]
@maelle I overlooked the invitation mail - it worked, thanks a ton. Slack with sebastian@hanss.info would be great

**Comment by maelle** [comment]
@bitbacchus what a relief! :relieved: 

I've just sent both of you invites to the rOpenSci slack workspace, so see you there! :wave: 

For context on the 2FA change here's a tech note draft that should be published next week: https://deploy-preview-334--ropensci.netlify.app/

**Comment by bitbacchus** [comment]
Everything is fine, now. Thanks :-)

**Comment by nldoc** [comment]
@maelle 
Sorry for responding that late.
I was on parental leave and did not follow up on most emails regarding work related stuff ;) 
I have enabled 2FA on github now. Can you please also re-add me to the organization/repo?
Thanks 🙏

**Comment by maelle** [comment]
@nldoc Congratulations! :egg: :turtle: :sparkles: 
I've now sent you an invite to the organization as well as a team with admin access to this repo.
